"""Redo

Revision ID: 18bd0c3e04be
Revises: 
Create Date: 2024-11-25 19:47:52.415769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import INTEGER, TEXT, BOOLEAN, JSON


# revision identifiers, used by Alembic.
revision = '18bd0c3e04be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'major_template',
        sa.Column('major', sa.String(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('school', sa.String(), nullable=True),
        sa.Column('credits', sa.Integer(), nullable=True),
        sa.Column('focus_track', sa.Boolean(), nullable=True),
        sa.Column('link', sa.String(), nullable=True),
        sa.Column('notes', sa.JSON(), nullable=True),
        sa.Column('required', sa.JSON(), nullable=True),
        sa.Column('pick_multiple', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('major', 'year')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('major_template')
    # ### end Alembic commands ###
