"""Major Template Table (Added Columns)

Revision ID: 82d692115457
Revises: 5a3ae11f4117
Create Date: 2024-11-19 21:56:54.581585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82d692115457'
down_revision = '5a3ae11f4117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_template', sa.Column('required', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('major_template', sa.Column('school', sa.VARCHAR(length=30), nullable=True))
    op.drop_column('major_template', 'classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_template', sa.Column('classes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('major_template', 'school')
    op.drop_column('major_template', 'required')
    # ### end Alembic commands ###
