"""Major Template Table (Added Columns)

Revision ID: 5a3ae11f4117
Revises: da82686fce6e
Create Date: 2024-11-12 22:17:52.127483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a3ae11f4117'
down_revision = 'da82686fce6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('major_template', sa.Column('credits', sa.INTEGER(), nullable=True))
    op.add_column('major_template', sa.Column('focus_track', sa.BOOLEAN(), nullable=True))
    op.add_column('major_template', sa.Column('link', sa.VARCHAR(length=100), nullable=True))
    op.add_column('major_template', sa.Column('notes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('major_template', sa.Column('pick_multiple', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.alter_column('major_template', 'classes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('major_template', 'classes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('major_template', 'pick_multiple')
    op.drop_column('major_template', 'notes')
    op.drop_column('major_template', 'link')
    op.drop_column('major_template', 'focus_track')
    op.drop_column('major_template', 'credits')
    # ### end Alembic commands ###
